rm -r "/Library/Application Support/VMware Fusion" ;
rm -r "/Library/Preferences/VMware Fusion" ;
rm -r "~/Library/Application Support/VMware Fusion" ;
rm -r "~/Library/Caches/com.vmware.fusion" ;
rm -r "~/Library/Preferences/VMware Fusion" ;
rm -r "~/Library/Preferences/com.vmware.fusion.LSSharedFileList.plist" ;
rm -r "~/Library/Preferences/com.vmware.fusion.LSSharedFileList.plist.lockfile" ;
rm -r "~/Library/Preferences/com.vmware.fusion.plist" ;
rm -r "~/Library/Preferences/com.vmware.fusion.plist.lockfile" ;
rm -r "~/Library/Preferences/com.vmware.fusionDaemon.plist" ;
rm -r "~/Library/Preferences/com.vmware.fusionDaemon.plist.lockfile" ;
rm -r "~/Library/Preferences/com.vmware.fusionStartMenu.plist" ;
rm -r "~/Library/Preferences/com.vmware.fusionStartMenu.plist.lockfile" ;
