[package]
name = "popper_common"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ariadne = "0.2.0"
colored = "2.1.0"
lazy_static = "1.4.0"
