[package]
name = "popper_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD:examples/ex1/Cargo.toml
popper = { path = "../../" }

=======
ariadne = "0.2.0"
>>>>>>> full-rewrite:crates/popper_common/Cargo.toml
