[package]
name = "popper_inkwell"
version = "0.1.0"
edition = "2021"


[dependencies]
popper_mir = { path = "../popper_mir" }
popper_common = { path = "../popper_common", features = ["hash"] }
inkwell = { version = "0.3.0", features = ["llvm17-0"] }
