[package]
name = "popper_lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
popper_semantic_analyzer = { path = "../popper_semantic_analyzer" }
popper_parser = { path = "../popper_parser" }
