[package]
name = "popper_sbc"
version = "0.1.0"
edition = "2021"
description = "Simple Bytecode Compiler for Popper Language"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
