[package]
name = "popper_semantic_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
popper_ast = { path = "../popper_ast" }
popper_error_core = { path = "../popper_error_core" }
popper_error_macro = { path = "../popper_error_macro" }
popper_index = { path = "../popper_index" }
